name: Install rok CLI
description: Installs the Immerok Cloud rok CLI.
inputs:
  version:
    description: "CLI version, e.g. 0.0.1"
    required: true
  accessToken:
    description: "Use 'rok auth generate' to generate an access token"
    required: true
runs:
  using: composite
  steps:
    - name: Download CLI
      shell: bash
      run: |
        wget "https://releases.immerok.cloud/rok/v${{ inputs.version }}/rok-linux-amd64.tar.gz"
        tar -xzf "rok-linux-amd64.tar.gz"
        rm -f "rok-linux-amd64.tar.gz"
        
        mkdir -p "$HOME/.local/bin"
        mv "rok-linux-amd64/rok" "$HOME/.local/bin/rok"
        echo "$HOME/.local/bin/rok" >> $GITHUB_PATH
        
        rm -rf "rok-linux-amd64/"
    - name: Log into Immerok Cloud
      shell: bash
      run: |
        rok auth login --token "${{ inputs.accessToken }}"
