name: Install rok CLI
description: Installs the Immerok Cloud rok CLI.
inputs:
  version:
    # FIXME Use this
    description: "CLI version, e.g. 0.0.1"
    required: true
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Download CLI
      shell: bash
      run: |
        brew tap immerok/tap
        brew install rok
